DET_TASKS = ('detection', 'det', 'detect')
SEG_TASKS = ('segmentation', 'semantic segmentation', 'seg')
ImageFormat = ('.png', '.jpg', '.jpeg', '.gif', '.tiff', '.svg', '.raw', 'webp', '.heic', '.heif')
LabelFormat = ('.csv', '.json', '.txt', '.xml', '.yaml', '.yml')
VideoFormat = ('.mp4', '.avi', '.mkv', '.wmv', '.flv', '.mov', 'rmvb')