wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/config_sgd.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/cross_repo.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/custom_imports.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/demo_train.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/example.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/learn_read_config.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/my_module.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/optimizer_cfg.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/predefined_var.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/refer_base_var.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/replace_data_root.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/replace_num_classes.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/resnet50_delete_key.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/resnet50_lr0.01.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/resnet50_runtime.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/resnet50.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/runtime_cfg.py
wget -P OpenMMLab/MMEngine/Config/codes/example_configs https://raw.githubusercontent.com/open-mmlab/mmengine/main/docs/resources/config/modify_base_var.py